filter:
    excluded_paths:
        - tests/*
        - vendor/*

checks:
    php:
        code_rating: true
        duplication: true

build:
    dependencies:
            before:
                - "find /home/scrutinizer/.phpenv/versions -name 'php.ini' -exec sed -i 's/^zend_extension_ts/;zend_extension_ts/' {} \\;"
    
    tests:
        override:
            -
                command: ./vendor/bin/phpunit --coverage-clover ./clover.xml
                coverage:
                    file: clover.xml
                    format: clover
