filter:
    excluded_paths:
        - tests/*
        - vendor/*

checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        redis: false
        docker: true

    dependencies:
        override:
            - composer install

    nodes:
        coverage:
            tests:
                override:
                    -   command: php vendor/bin/phpunit --coverage-clover=coverage.xml
                        coverage:
                            file: coverage.xml
                            format: clover
